name: ConvertPlugin
version: '${project.version}'
main: com.convert.ConvertPlugin
api-version: '1.20'
description: Eşya convert sistemi
author: ConvertPlugin

commands:
  convert:
    description: Eşyaları paraya çevir
    usage: /convert
    aliases: [sat, sell]
  convertadmin:
    description: Convert admin komutları
    usage: /convertadmin <fiyat|liste|reload>
    permission: convert.admin

permissions:
  convert.kullan:
    description: /convert komutunu kullanabilir
    default: true
  convert.admin:
    description: Admin komutlarını kullanabilir
    default: op
